name = "PLayingWithFabric17"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd6b6a6d6697851d4f98d5d220ca21340d37e11c0ad9e473c51bfcbf8f593ebf"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
