name = "PLayingWithFabric17"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cbcdd917188560cd1391dd2d32ab076511478b05cd2cd6dae8d917b5bbd4cb5"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
