name = "PLayingWithFabric17"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61745c20b38d28b8a07734cc97c7fee1c70d7d5b5b6ac0e9358dbf2f2fd401da"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
