name = "PLayingWithFabric17"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea8de05d03c0dc9be253bd69bfcf7d48e774cc56949d095e4dbcc061d0fababb"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
